# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/HeatGeo',
                'doc_host': 'https://guillaumehu.github.io',
                'git_url': 'https://github.com/guillaumehu/HeatGeo',
                'lib_path': 'HeatGeo'},
  'syms': {'HeatGeo.core': {'HeatGeo.core.foo': ('core.html#foo', 'HeatGeo/core.py')}}}
