# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: long
    cpus_per_task: 2
    mem_gb: 20
    timeout_min: 1440 # 24h
    array_parallelism: 20 # max num of tasks to run in parallel (via job array)
    setup:
      - "module purge"
      - "module load miniconda/3"
      - "conda activate metric_emb"
